-- 添加精确时间戳字段
-- 为所有用户相关功能添加准确的时间戳

-- 1. 心理测评表添加时间戳
ALTER TABLE psych_tests 
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- 2. 每日打卡表添加时间戳
ALTER TABLE daily_checkin 
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- 3. 生活计划表添加时间戳
ALTER TABLE recovery_plans 
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- 4. 用户记忆表添加时间戳
ALTER TABLE user_memories 
ADD COLUMN last_accessed_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- 5. 用户洞察表添加时间戳
ALTER TABLE user_insights 
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN last_profile_update DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- 6. 用户画像表添加时间戳（如果存在）
-- ALTER TABLE user_profiles 
-- ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
-- ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
